apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.labels.app }}
    tag: {{ .Values.labels.tag }}
  name: {{ .Values.labels.app }}-{{ .Values.labels.tag }}
  namespace:  {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replica.count }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      tag: {{ .Values.labels.tag }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        tag: {{ .Values.labels.tag }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name:  {{ .Values.labels.app }}-{{ .Values.labels.tag }}
