apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.labels.app }}
    tag: {{ .Values.labels.tag }}
  name: {{ .Values.labels.app }}-{{ .Values.labels.tag }}
  namespace:  {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.labels.app }}
    tag: {{ .Values.labels.tag }}
  type: {{ .Values.service.type }}
