namespace:
   name: demo

replica:
   count: 3

labels:
   app: nginx
   tag: alpine

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

resources: 
  cpu: 50m
  memory: 256Mi

service:
   type: NodePort
   port: 8111
   targetPort: 80
   nodePort: 30080

configmap:
   data: "version: alpine"
